### ISSUE TITLE
README woefully out of date

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/doltpy#16]
I think we should focus on doltpy.core over doltpy.etl to get people eased into the interface. At the start, it's more likely that people will come for simple shit like:

1. I want to read a table into a dataframe
2. I want to import a CSV
3. I want to run a SQL query and get a dictionary of the results

It's much less likely that they'll want a full service importer that they can integrate with Airflow easily. We should ease them up to that.

**Comment by oscarbatori** [comment]
The README is actually not out of date, it just emphasizes shims as the entry point, rather than the API. I agree, but I actually want to figure out how to generate good docs from the docstrings, and use that, and then make the README a copy of what we put up as a tutorial/getting started on the docs site.

**Comment by oscarbatori** [comment]
As per my above comment we now have a brief up to date README that points folks at our docs site where more detail is warranted.
